import { extractCodexTurnIdentityFromBody } from "../adapters/chatgpt-web/browser-request-contract";
import {
  createResponseContinuationScope,
  type ResponseContinuationScope,
} from "./state";

/** One origin namespace for every response ID generated by the local NEKODEX bridge. */
export const NEKODEX_LOCAL_RESPONSE_NAMESPACE = "nekodex-local-responses-v1";

function record(value: unknown): Record<string, unknown> | undefined {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : undefined;
}

/**
 * Derive continuation ownership from the original, unexpanded Responses body. The native
 * passthrough layer has no authoritative launcher account-routing key, so this shared contract
 * deliberately does not fabricate one. Server retention must call the same helper for parity.
 */
export function createResponseContinuationScopeFromBody(
  body: unknown,
  providerNamespace = NEKODEX_LOCAL_RESPONSE_NAMESPACE,
): ResponseContinuationScope | undefined {
  const identity = extractCodexTurnIdentityFromBody(body);
  const raw = record(body);
  return createResponseContinuationScope({
    providerNamespace,
    threadId: identity.threadId,
    turnId: identity.turnId,
    ...(typeof raw?.prompt_cache_key === "string"
      ? { promptCacheKey: raw.prompt_cache_key }
      : {}),
  });
}
