import { extractCodexTurnIdentityFromBody } from "../adapters/chatgpt-web/browser-request-contract";
import { jsonRecord } from "../lib/json-record";
import {
  createResponseContinuationScope,
  type ResponseContinuationScope,
} from "./continuation-scope";

/** One origin namespace for every response ID generated by the local NEKODEX bridge. */
export const NEKODEX_LOCAL_RESPONSE_NAMESPACE = "nekodex-local-responses-v1";

/**
 * Derive continuation ownership from the original, unexpanded Responses body. The native
 * passthrough layer has no authoritative launcher account-routing key, so this shared contract
 * deliberately does not fabricate one. Server retention must call the same helper for parity.
 */
export function createResponseContinuationScopeFromBody(
  body: unknown,
  providerNamespace = NEKODEX_LOCAL_RESPONSE_NAMESPACE,
): ResponseContinuationScope | undefined {
  const identity = extractCodexTurnIdentityFromBody(body);
  const raw = jsonRecord(body);
  return createResponseContinuationScope({
    providerNamespace,
    threadId: identity.threadId,
    turnId: identity.turnId,
    ...(typeof raw?.prompt_cache_key === "string"
      ? { promptCacheKey: raw.prompt_cache_key }
      : {}),
  });
}
