const { contextBridge, ipcRenderer } = require("electron");

function subscription(channel, listener) {
  const wrapped = (_event, value) => listener(value);
  ipcRenderer.on(channel, wrapped);
  return () => ipcRenderer.removeListener(channel, wrapped);
}

contextBridge.exposeInMainWorld("codexWebLauncher", {
  snapshot: () => ipcRenderer.invoke("launcher:snapshot"),
  setLanguage: (language) => ipcRenderer.invoke("launcher:set-language", language),
  openSocial: (target) => ipcRenderer.invoke("launcher:open-social", target),
  completeOnboarding: (language, browserInteractionMode) => ipcRenderer.invoke(
    "launcher:complete-onboarding",
    language,
    browserInteractionMode,
  ),
  openExternal: (url) => ipcRenderer.invoke("launcher:open-external", url),
  setBrowserBounds: (bounds) => ipcRenderer.invoke("launcher:browser-bounds", bounds),
  setBrowserSurfaceActive: (active) => ipcRenderer.invoke("launcher:browser-surface-active", active),
  showBrowser: () => ipcRenderer.invoke("launcher:browser-show"),
  hideBrowser: () => ipcRenderer.invoke("launcher:browser-hide"),
  navigateBrowser: (action) => ipcRenderer.invoke("launcher:browser-navigate", action),
  zoomBrowser: (action) => ipcRenderer.invoke("launcher:browser-zoom", action),
  selectBrowserTab: (tabId) => ipcRenderer.invoke("launcher:browser-tab-select", tabId),
  closeBrowserTab: (tabId) => ipcRenderer.invoke("launcher:browser-tab-close", tabId),
  copyManualPrompt: (tabId) => ipcRenderer.invoke("launcher:manual-prompt-copy", tabId),
  confirmManualSent: (tabId) => ipcRenderer.invoke("launcher:manual-prompt-sent", tabId),
  openLogin: () => ipcRenderer.invoke("launcher:browser-login"),
  openPasskeyLogin: () => ipcRenderer.invoke("launcher:browser-passkey-login"),
  continuePasskeyLogin: () => ipcRenderer.invoke("launcher:browser-passkey-login-continue"),
  revealPasskeyLogin: () => ipcRenderer.invoke("launcher:browser-passkey-login-reveal"),
  cancelPasskeyLogin: () => ipcRenderer.invoke("launcher:browser-passkey-login-cancel"),
  openExistingChromeLogin: () => ipcRenderer.invoke("launcher:browser-existing-chrome-login"),
  cancelExistingChromeLogin: () => ipcRenderer.invoke("launcher:browser-existing-chrome-login-cancel"),
  allowExistingChromeFileAccess: () => ipcRenderer.invoke("launcher:browser-existing-chrome-file-access"),
  copyExistingChromeSettingsAddress: () => ipcRenderer.invoke("launcher:browser-existing-chrome-settings-copy"),
  logoutChatGpt: () => ipcRenderer.invoke("launcher:browser-logout"),
  dismissSessionReminder: () => ipcRenderer.invoke("launcher:session-reminder-dismiss"),
  smokeTest: () => ipcRenderer.invoke("launcher:browser-smoke"),
  verifyMcp: () => ipcRenderer.invoke("launcher:mcp-verify"),
  doctor: () => ipcRenderer.invoke("launcher:doctor"),
  routeDiagnostics: () => ipcRenderer.invoke("launcher:route-diagnostics"),
  cancelTurns: () => ipcRenderer.invoke("launcher:cancel-turns"),
  uninstallIntegration: () => ipcRenderer.invoke("launcher:uninstall-integration"),
  setupCore: () => ipcRenderer.invoke("launcher:setup-core"),
  setupHermes: (input) => ipcRenderer.invoke("launcher:setup-hermes", input),
  setupMcp: (input) => ipcRenderer.invoke("launcher:setup-mcp", input),
  setMcpStep: (step) => ipcRenderer.invoke("launcher:set-mcp-step", step),
  setAutostart: (enabled) => ipcRenderer.invoke("launcher:autostart", enabled),
  setBiggerContext: (enabled) => ipcRenderer.invoke("launcher:bigger-context", enabled),
  setAsyncToolOperations: (enabled) => ipcRenderer.invoke("launcher:async-tool-operations", enabled),
  setFreshConversation: (enabled) => ipcRenderer.invoke("launcher:fresh-conversation", enabled),
  setWebSubagents: (enabled) => ipcRenderer.invoke("launcher:web-subagents", enabled),
  setSkillAttachments: (enabled) => ipcRenderer.invoke("launcher:skill-attachments", enabled),
  cancelContextChange: () => ipcRenderer.invoke("launcher:cancel-context-change"),
  confirmCodexModels: () => ipcRenderer.invoke("launcher:confirm-codex-models"),
  setZeroRiskPro: (enabled) => ipcRenderer.invoke("launcher:zero-risk-pro", enabled),
  accounts: () => ipcRenderer.invoke("launcher:accounts"),
  addAccount: label => ipcRenderer.invoke("launcher:account-add", label),
  selectAccount: id => ipcRenderer.invoke("launcher:account-select", id),
  setAccountEnabled: (id, enabled) => ipcRenderer.invoke("launcher:account-enabled", id, enabled),
  setAccountProxy: (id, value) => ipcRenderer.invoke("launcher:account-proxy", id, value),
  setAccountSafety: (id, policy) => ipcRenderer.invoke("launcher:account-safety", id, policy),
  resumeAccount: (id) => ipcRenderer.invoke("launcher:account-resume", id),
  setAccountMode: mode => ipcRenderer.invoke("launcher:account-mode", mode),
  openAccountLogin: id => ipcRenderer.invoke("launcher:account-login", id),
  checkAccount: (id, connector) => ipcRenderer.invoke("launcher:account-check", id, connector),
  setBrowserCapacity: (value) => ipcRenderer.invoke("launcher:browser-capacity", value),
  setCompactionModel: (value) => ipcRenderer.invoke("launcher:compaction-model", value),
  setProModelVersion: (version) => ipcRenderer.invoke("launcher:pro-model-version", version),
  setBrowserInteractionMode: (mode) => ipcRenderer.invoke("launcher:browser-interaction-mode", mode),
  setPreference: (key, value) => ipcRenderer.invoke("launcher:set-preference", key, value),
  setSidebarState: (state) => ipcRenderer.invoke("launcher:sidebar-state", state),
  usage: (days) => ipcRenderer.invoke("launcher:usage", days),
  logs: (limit) => ipcRenderer.invoke("launcher:logs", limit),
  exportLogs: () => ipcRenderer.invoke("launcher:export-logs"),
  installUpdate: () => ipcRenderer.invoke("launcher:update-install"),
  recheckUpdate: () => ipcRenderer.invoke("launcher:update-recheck"),
  readUpdateRequestRevision: () => ipcRenderer.invoke("launcher:update-request-revision"),
  onOpenUpdates: (listener) => subscription("launcher:open-updates", listener),
  windowState: () => ipcRenderer.invoke("launcher:window-state"),
  windowControl: (action) => ipcRenderer.send("launcher:window-control", action),
  onWindowStateChanged: (listener) => subscription("launcher:window-state-changed", listener),
  onStateChanged: (listener) => subscription("launcher:state-changed", listener),
  onBrowserState: (listener) => subscription("launcher:browser-state", listener),
  onOperation: (listener) => subscription("launcher:operation", listener),
  onLog: (listener) => subscription("launcher:log", listener),
  onUpdateState: (listener) => subscription("launcher:update-state", listener),
});
