import type { Language } from "./types";

const en = {
  title: "Updates", subtitle: "Keep NEKODEX up to date, right here.", current: "Installed version",
  available: "An update is ready", latest: "You're up to date", idle: "Check for a new version",
  checking: "Checking GitHub…", downloading: "Downloading update…", verifying: "Checking the update package…",
  installing: "Restarting to finish the update…", check: "Check for updates", install: "Download and restart",
  retry: "Try again", failed: "Update couldn't finish", disabled: "Updates are available in the installed app",
  disabledBody: "Open an installed NEKODEX build to download and install updates. This development copy will not replace your app.",
  wait: "Finish active tasks and setup operations before updating.", cooldown: "You can check again in a minute.",
  automatic: "NEKODEX checks GitHub when it starts. Updates are installed only when you choose to update.",
  preserved: "Your accounts and settings stay in place. The package is verified before installation.",
  restart: "NEKODEX will close and reopen automatically. No DMG installation is needed.",
  progress: "Download progress", source: "Source: Froraut/NEKODEX on GitHub",
};
type UpdateCopy = { [K in keyof typeof en]: string };
const copies: Record<Language, UpdateCopy> = {
  ru: {
    title: "Обновления", subtitle: "Обновляйте NEKODEX прямо здесь.", current: "Установленная версия",
    available: "Доступно обновление", latest: "Установлена последняя версия", idle: "Проверить новую версию",
    checking: "Проверка GitHub…", downloading: "Загрузка обновления…", verifying: "Проверка пакета обновления…",
    installing: "Перезапуск для завершения обновления…", check: "Проверить обновления", install: "Скачать и перезапустить",
    retry: "Повторить", failed: "Не удалось завершить обновление", disabled: "Обновления доступны в установленном приложении",
    disabledBody: "Откройте установленный NEKODEX для загрузки и установки обновлений. Эта копия для разработки не заменит ваше приложение.",
    wait: "Перед обновлением завершите активные задачи и операции настройки.", cooldown: "Повторная проверка доступна через минуту.",
    automatic: "NEKODEX проверяет GitHub при запуске. Обновление устанавливается только по вашему выбору.",
    preserved: "Аккаунты и настройки сохраняются. Пакет проверяется перед установкой.",
    restart: "NEKODEX автоматически закроется и откроется снова. Устанавливать DMG вручную не нужно.",
    progress: "Ход загрузки", source: "Источник: Froraut/NEKODEX на GitHub",
  },
  en,
  "zh-CN": {
    title: "更新", subtitle: "直接在这里更新 NEKODEX。", current: "已安装版本",
    available: "有新版本可用", latest: "已是最新版本", idle: "检查新版本", checking: "正在检查 GitHub…",
    downloading: "正在下载更新…", verifying: "正在验证更新包…", installing: "正在重启以完成更新…",
    check: "检查更新", install: "下载并重启", retry: "重试", failed: "更新未能完成",
    disabled: "请在已安装的应用中更新", disabledBody: "打开已安装的 NEKODEX 下载并安装更新。此开发副本不会替换现有应用。",
    wait: "请先完成正在运行的任务和设置操作。", cooldown: "一分钟后可再次检查。",
    automatic: "NEKODEX 启动时会检查 GitHub，仅在你选择更新后安装。",
    preserved: "账户和设置将保留。安装前会验证更新包。", restart: "NEKODEX 会自动关闭并重新打开，无需手动安装 DMG。",
    progress: "下载进度", source: "来源：GitHub 上的 Froraut/NEKODEX",
  },
  "zh-TW": {
    title: "更新", subtitle: "直接在這裡更新 NEKODEX。", current: "已安裝版本",
    available: "有新版本可用", latest: "已是最新版本", idle: "檢查新版本", checking: "正在檢查 GitHub…",
    downloading: "正在下載更新…", verifying: "正在驗證更新套件…", installing: "正在重新啟動以完成更新…",
    check: "檢查更新", install: "下載並重新啟動", retry: "重試", failed: "更新未能完成",
    disabled: "請在已安裝的應用程式中更新", disabledBody: "開啟已安裝的 NEKODEX 下載並安裝更新。此開發副本不會取代現有應用程式。",
    wait: "請先完成執行中的任務和設定操作。", cooldown: "一分鐘後可再次檢查。",
    automatic: "NEKODEX 啟動時會檢查 GitHub，僅在您選擇更新後安裝。",
    preserved: "帳號和設定會保留。安裝前會驗證更新套件。", restart: "NEKODEX 會自動關閉並重新開啟，無需手動安裝 DMG。",
    progress: "下載進度", source: "來源：GitHub 上的 Froraut/NEKODEX",
  },
  ja: {
    title: "アップデート", subtitle: "NEKODEX をこの画面から更新できます。", current: "インストール済みバージョン",
    available: "新しいバージョンがあります", latest: "最新の状態です", idle: "新しいバージョンを確認",
    checking: "GitHub を確認中…", downloading: "更新をダウンロード中…", verifying: "更新パッケージを検証中…",
    installing: "更新を完了するために再起動中…", check: "更新を確認", install: "ダウンロードして再起動",
    retry: "再試行", failed: "更新を完了できませんでした", disabled: "インストール済みアプリで更新できます",
    disabledBody: "インストール済みの NEKODEX を開いて更新してください。この開発用コピーはアプリを置き換えません。",
    wait: "実行中のタスクと設定操作を完了してから更新してください。", cooldown: "1分後に再確認できます。",
    automatic: "NEKODEX は起動時に GitHub を確認します。更新を選択した場合のみインストールします。",
    preserved: "アカウントと設定は保持されます。インストール前にパッケージを検証します。",
    restart: "NEKODEX は自動的に終了して再起動します。DMG の手動インストールは不要です。",
    progress: "ダウンロードの進行状況", source: "配信元：GitHub の Froraut/NEKODEX",
  },
  ko: {
    title: "업데이트", subtitle: "여기에서 NEKODEX를 최신 상태로 유지하세요.", current: "설치된 버전",
    available: "새 업데이트가 있습니다", latest: "최신 버전입니다", idle: "새 버전 확인",
    checking: "GitHub 확인 중…", downloading: "업데이트 다운로드 중…", verifying: "업데이트 패키지 확인 중…",
    installing: "업데이트를 완료하기 위해 다시 시작하는 중…", check: "업데이트 확인", install: "다운로드 후 다시 시작",
    retry: "다시 시도", failed: "업데이트를 완료하지 못했습니다", disabled: "설치된 앱에서 업데이트할 수 있습니다",
    disabledBody: "설치된 NEKODEX를 열어 업데이트를 다운로드하고 설치하세요. 이 개발용 복사본은 앱을 교체하지 않습니다.",
    wait: "실행 중인 작업과 설정을 완료한 후 업데이트하세요.", cooldown: "1분 후 다시 확인할 수 있습니다.",
    automatic: "NEKODEX는 시작할 때 GitHub를 확인합니다. 업데이트를 선택한 경우에만 설치됩니다.",
    preserved: "계정과 설정이 유지됩니다. 설치 전에 패키지를 검증합니다.", restart: "NEKODEX가 자동으로 종료되고 다시 열립니다. DMG를 직접 설치할 필요가 없습니다.",
    progress: "다운로드 진행률", source: "출처: GitHub의 Froraut/NEKODEX",
  },
};
export const updateCopyFor = (language: Language): UpdateCopy => copies[language];
