import type { Language } from "./types";

const en = {
  cancel: "Cancel update",
  cancelling: "Cancelling update…",
  cancellingBody: "Stopping preparation. Your installed app stays in place; downloaded data is kept for retry.",
  cancelTooLate: "Installation has already started. Wait for NEKODEX to reopen.",

  stageDownload: "Download", stageVerify: "Verify", stageRestart: "Restart",
  title: "Updates", subtitle: "Keep NEKODEX up to date, right here.", current: "Installed version",
  available: "An update is ready", latest: "You're up to date", idle: "Check for a new version",
  checking: "Checking GitHub…", downloading: "Downloading update…", verifying: "Checking the update package…",
  installing: "Restarting to finish the update…", check: "Check for updates", install: "Download and restart",
  retryCheck: "Retry update check", failed: "Update couldn't finish", disabled: "Updates are available in the installed app",
  disabledBody: "Open an installed NEKODEX build to download and install updates. This development copy will not replace your app.",
  wait: "Finish active tasks and setup operations before updating.", cooldown: "You can check again in a minute.",
  automatic: "NEKODEX checks GitHub when it starts and every few hours. Updates are installed only when you choose to update.",
    previousFailed: "The last update attempt didn't finish, so NEKODEX kept the installed version. Reason: {message}",
  preserved: "Your accounts and settings stay in place. The package is verified before installation.",
  restart: "NEKODEX will close to install the update, then reopen. If final activation is still needed, it will show Restart NEKODEX; use it when your work is finished. No DMG installation is needed.",
  downloadRemaining: "About {duration} remaining in download",
  progress: "Download progress", source: "Source: Froraut/NEKODEX on GitHub",
};
type UpdateCopy = { [K in keyof typeof en]: string };
const copies: Record<Language, UpdateCopy> = {
  ru: {
  cancel: "Отменить обновление",
  cancelling: "Отмена обновления…",
  cancellingBody: "Останавливаем подготовку. Установленное приложение остаётся на месте; загруженные данные сохраняются для повтора.",
  cancelTooLate: "Установка уже началась. Дождитесь повторного открытия NEKODEX.",

  stageDownload: "Загрузка", stageVerify: "Проверка", stageRestart: "Перезапуск",
    title: "Обновления", subtitle: "Обновляйте NEKODEX прямо здесь.", current: "Установленная версия",
    available: "Доступно обновление", latest: "Установлена последняя версия", idle: "Проверить новую версию",
    checking: "Проверка GitHub…", downloading: "Загрузка обновления…", verifying: "Проверка пакета обновления…",
    installing: "Перезапуск для завершения обновления…", check: "Проверить обновления", install: "Скачать и перезапустить",
    retryCheck: "Повторить проверку обновлений", failed: "Не удалось завершить обновление", disabled: "Обновления доступны в установленном приложении",
    disabledBody: "Откройте установленный NEKODEX для загрузки и установки обновлений. Эта копия для разработки не заменит ваше приложение.",
    wait: "Перед обновлением завершите активные задачи и операции настройки.", cooldown: "Повторная проверка доступна через минуту.",
    automatic: "NEKODEX проверяет GitHub при запуске и раз в несколько часов. Обновление устанавливается только по вашему выбору.",
    previousFailed: "Предыдущая попытка обновления не завершилась, поэтому NEKODEX оставил установленную версию. Причина: {message}",
    preserved: "Аккаунты и настройки сохраняются. Пакет проверяется перед установкой.",
    restart: "NEKODEX закроется для установки обновления, а затем откроется снова. Если для окончательной активации потребуется ещё один перезапуск, появится кнопка «Перезапустить NEKODEX» — нажмите её после завершения работы. Устанавливать DMG вручную не нужно.",
    downloadRemaining: "До конца загрузки примерно {duration}",
    progress: "Ход загрузки", source: "Источник: Froraut/NEKODEX на GitHub",
  },
  en,
  "zh-CN": {
  cancel: "取消更新",
  cancelling: "正在取消更新…",
  cancellingBody: "正在停止准备。已安装的应用保持不变；已下载的数据将保留以便重试。",
  cancelTooLate: "安装已开始。请等待 NEKODEX 重新打开。",

  stageDownload: "下载", stageVerify: "验证", stageRestart: "重启",
    title: "更新", subtitle: "直接在这里更新 NEKODEX。", current: "已安装版本",
    available: "有新版本可用", latest: "已是最新版本", idle: "检查新版本", checking: "正在检查 GitHub…",
    downloading: "正在下载更新…", verifying: "正在验证更新包…", installing: "正在重启以完成更新…",
    check: "检查更新", install: "下载并重启", retryCheck: "重新检查更新", failed: "更新未能完成",
    disabled: "请在已安装的应用中更新", disabledBody: "打开已安装的 NEKODEX 下载并安装更新。此开发副本不会替换现有应用。",
    wait: "请先完成正在运行的任务和设置操作。", cooldown: "一分钟后可再次检查。",
    automatic: "NEKODEX 会在启动时及每隔几小时检查 GitHub，仅在你选择更新后安装。",
    previousFailed: "上次更新未能完成，NEKODEX 已保留当前安装的版本。原因：{message}",
    preserved: "账户和设置将保留。安装前会验证更新包。", restart: "NEKODEX 会关闭以安装更新，然后重新打开。如果最终激活仍需重启，应用会显示“重新启动 NEKODEX”；请在完成工作后使用它。无需手动安装 DMG。",
    downloadRemaining: "下载预计还需 {duration}",
    progress: "下载进度", source: "来源：GitHub 上的 Froraut/NEKODEX",
  },
  "zh-TW": {
  cancel: "取消更新",
  cancelling: "正在取消更新…",
  cancellingBody: "正在停止準備。已安裝的應用程式保持不變；已下載的資料會保留以便重試。",
  cancelTooLate: "安裝已開始。請等待 NEKODEX 重新開啟。",

  stageDownload: "下載", stageVerify: "驗證", stageRestart: "重新啟動",
    title: "更新", subtitle: "直接在這裡更新 NEKODEX。", current: "已安裝版本",
    available: "有新版本可用", latest: "已是最新版本", idle: "檢查新版本", checking: "正在檢查 GitHub…",
    downloading: "正在下載更新…", verifying: "正在驗證更新套件…", installing: "正在重新啟動以完成更新…",
    check: "檢查更新", install: "下載並重新啟動", retryCheck: "重新檢查更新", failed: "更新未能完成",
    disabled: "請在已安裝的應用程式中更新", disabledBody: "開啟已安裝的 NEKODEX 下載並安裝更新。此開發副本不會取代現有應用程式。",
    wait: "請先完成執行中的任務和設定操作。", cooldown: "一分鐘後可再次檢查。",
    automatic: "NEKODEX 會在啟動時及每隔幾小時檢查 GitHub，僅在您選擇更新後安裝。",
    previousFailed: "上次更新未能完成，NEKODEX 已保留目前安裝的版本。原因：{message}",
    preserved: "帳號和設定會保留。安裝前會驗證更新套件。", restart: "NEKODEX 會關閉以安裝更新，然後重新開啟。如果最終啟用仍需重新啟動，應用程式會顯示「重新啟動 NEKODEX」；請在完成工作後使用。無需手動安裝 DMG。",
    downloadRemaining: "下載預計還需 {duration}",
    progress: "下載進度", source: "來源：GitHub 上的 Froraut/NEKODEX",
  },
  ja: {
  cancel: "更新をキャンセル",
  cancelling: "更新をキャンセル中…",
  cancellingBody: "準備を停止しています。インストール済みアプリは変更されず、ダウンロード済みデータは再試行のために保持されます。",
  cancelTooLate: "インストールはすでに開始されています。NEKODEX が再び開くまでお待ちください。",

  stageDownload: "ダウンロード", stageVerify: "検証", stageRestart: "再起動",
    title: "アップデート", subtitle: "NEKODEX をこの画面から更新できます。", current: "インストール済みバージョン",
    available: "新しいバージョンがあります", latest: "最新の状態です", idle: "新しいバージョンを確認",
    checking: "GitHub を確認中…", downloading: "更新をダウンロード中…", verifying: "更新パッケージを検証中…",
    installing: "更新を完了するために再起動中…", check: "更新を確認", install: "ダウンロードして再起動",
    retryCheck: "アップデート確認を再試行", failed: "更新を完了できませんでした", disabled: "インストール済みアプリで更新できます",
    disabledBody: "インストール済みの NEKODEX を開いて更新してください。この開発用コピーはアプリを置き換えません。",
    wait: "実行中のタスクと設定操作を完了してから更新してください。", cooldown: "1分後に再確認できます。",
    automatic: "NEKODEX は起動時と数時間ごとに GitHub を確認します。更新を選択した場合のみインストールします。",
    previousFailed: "前回の更新は完了しなかったため、NEKODEX はインストール済みのバージョンを維持しました。理由：{message}",
    preserved: "アカウントと設定は保持されます。インストール前にパッケージを検証します。",
    restart: "NEKODEX はアップデートのインストール時に終了し、その後もう一度開きます。最終的な有効化にもう一度再起動が必要な場合は「NEKODEX を再起動」が表示されるので、作業が終わってから実行してください。DMG の手動インストールは不要です。",
    downloadRemaining: "ダウンロード完了まで約 {duration}",
    progress: "ダウンロードの進行状況", source: "配信元：GitHub の Froraut/NEKODEX",
  },
  ko: {
  cancel: "업데이트 취소",
  cancelling: "업데이트 취소 중…",
  cancellingBody: "준비를 중지하고 있습니다. 설치된 앱은 유지되며 다운로드한 데이터는 재시도를 위해 보관됩니다.",
  cancelTooLate: "설치가 이미 시작되었습니다. NEKODEX가 다시 열릴 때까지 기다려 주세요.",

  stageDownload: "다운로드", stageVerify: "검증", stageRestart: "다시 시작",
    title: "업데이트", subtitle: "여기에서 NEKODEX를 최신 상태로 유지하세요.", current: "설치된 버전",
    available: "새 업데이트가 있습니다", latest: "최신 버전입니다", idle: "새 버전 확인",
    checking: "GitHub 확인 중…", downloading: "업데이트 다운로드 중…", verifying: "업데이트 패키지 확인 중…",
    installing: "업데이트를 완료하기 위해 다시 시작하는 중…", check: "업데이트 확인", install: "다운로드 후 다시 시작",
    retryCheck: "업데이트 확인 다시 시도", failed: "업데이트를 완료하지 못했습니다", disabled: "설치된 앱에서 업데이트할 수 있습니다",
    disabledBody: "설치된 NEKODEX를 열어 업데이트를 다운로드하고 설치하세요. 이 개발용 복사본은 앱을 교체하지 않습니다.",
    wait: "실행 중인 작업과 설정을 완료한 후 업데이트하세요.", cooldown: "1분 후 다시 확인할 수 있습니다.",
    automatic: "NEKODEX는 시작할 때와 몇 시간마다 GitHub를 확인합니다. 업데이트를 선택한 경우에만 설치됩니다.",
    previousFailed: "지난 업데이트가 완료되지 않아 NEKODEX가 설치된 버전을 유지했습니다. 이유: {message}",
    preserved: "계정과 설정이 유지됩니다. 설치 전에 패키지를 검증합니다.", restart: "NEKODEX가 업데이트 설치를 위해 닫힌 뒤 다시 열립니다. 최종 활성화에 다시 시작이 더 필요하면 ‘NEKODEX 다시 시작’이 표시되므로 작업을 마친 뒤 사용하세요. DMG를 직접 설치할 필요는 없습니다.",
    downloadRemaining: "다운로드 완료까지 약 {duration} 남음",
    progress: "다운로드 진행률", source: "출처: GitHub의 Froraut/NEKODEX",
  },
};
export const updateCopyFor = (language: Language): UpdateCopy => copies[language];
