import type { Language } from "./types";

const en = {
  session: {
    verificationUnavailable: "Verification unavailable",
    verificationUnavailableBody: "NEKODEX could not check this session. This does not mean the account is signed out.",
    lastVerifiedAt: "Last verified {time}",
    verifiedCurrent: "Verified in the current session",
    verificationStale: "Last known verification; current state is unknown",
    signedOut: "Signed out",
    retryVerification: "Retry verification",
    checkingVerification: "Checking…",
  },
  portfolio: {
    refreshAll: "Refresh account limits",
    refreshing: "Refreshing account limits…",
    summary: "Current {updated} · Earlier {retained} · Unavailable {unavailable} · Skipped {skipped}",
    updatedCount: "Current evidence: {count}",
    retainedCount: "Last known retained: {count}",
    unavailableCount: "Unavailable: {count}",
    skippedCount: "Skipped: {count}",
    quotaCurrent: "Current provider-reported windows; not total account capacity",
    quotaLastKnown: "Last known provider-reported windows; not current or total account capacity",
    quotaUnavailable: "Provider limits could not be checked",
    checkedAt: "Provider data from {time}",
    retainedAt: "Last successful check {time}",
  },
  recovery: {
    webTransportTitle: "Web transport needs attention",
    webTransportBody: "Native models remain available. Repair checks only the Web tunnel and does not prove that a tool executed.",
    repairAction: "Repair Web transport",
    repairing: "Repairing Web transport…",
    recovered: "Web transport was repaired and verified again",
    stillUnavailable: "Repair finished, but Web transport is still unavailable",
    couldNotVerify: "Repair finished, but readiness could not be verified",
    nativePreserved: "Native work remains available during this repair",
    fullSetupAction: "Run full connection setup",
    fullSetupBody: "Reconfigure saved credentials and connections, then verify them. This is broader than transport repair and does not prove a real tool execution.",
    blockedActiveWork: "Wait for active work to finish before repairing Web transport",
  },
  insights: {
    title: "Observed performance",
    body: "Comparison uses local recorded outcomes for the selected period. It is not a provider allowance or routing recommendation.",
    completionRate: "Known-outcome completion rate",
    median: "Median duration",
    p95: "95th percentile duration",
    knownOutcomes: "Known outcomes: {count}",
    durationSamples: "Duration samples: {count}",
    coverage: "Observed sample coverage: {count}",
    insufficientEvidence: "Insufficient evidence for a reliable comparison",
    unknownIdentity: "Account or model identity was not reported and was not guessed",
    noComparison: "No comparable observed groups in this period",
    notBestModel: "These observations do not identify or recommend a best model",
  },
} as const;

type StringShape<T> = { [K in keyof T]: T[K] extends string ? string : StringShape<T[K]> };
export type WorkflowCopy = StringShape<typeof en>;

const ru: WorkflowCopy = {
  session: {
    verificationUnavailable: "Проверка недоступна",
    verificationUnavailableBody: "NEKODEX не смог проверить этот сеанс. Это не означает, что выполнен выход из аккаунта.",
    lastVerifiedAt: "Последняя проверка: {time}",
    verifiedCurrent: "Проверено в текущем сеансе",
    verificationStale: "Последнее известное состояние; текущее состояние неизвестно",
    signedOut: "Выполнен выход",
    retryVerification: "Повторить проверку",
    checkingVerification: "Проверка…",
  },
  portfolio: {
    refreshAll: "Обновить лимиты аккаунтов",
    refreshing: "Обновление лимитов аккаунтов…",
    summary: "Актуальные данные: {updated} · Более ранние: {retained} · Недоступно: {unavailable} · Пропущено: {skipped}",
    updatedCount: "Актуальные данные: {count}",
    retainedCount: "Сохранены последние данные: {count}",
    unavailableCount: "Недоступно: {count}",
    skippedCount: "Пропущено: {count}",
    quotaCurrent: "Текущие окна, сообщённые провайдером; это не полная ёмкость аккаунта",
    quotaLastKnown: "Последние известные окна провайдера; это не текущая и не полная ёмкость аккаунта",
    quotaUnavailable: "Не удалось проверить лимиты провайдера",
    checkedAt: "Данные провайдера от {time}",
    retainedAt: "Последняя успешная проверка: {time}",
  },
  recovery: {
    webTransportTitle: "Web-транспорт требует внимания",
    webTransportBody: "Нативные модели остаются доступны. Восстановление проверяет только Web-туннель и не доказывает выполнение инструмента.",
    repairAction: "Восстановить Web-транспорт",
    repairing: "Восстановление Web-транспорта…",
    recovered: "Web-транспорт восстановлен и повторно проверен",
    stillUnavailable: "Восстановление завершено, но Web-транспорт всё ещё недоступен",
    couldNotVerify: "Восстановление завершено, но готовность проверить не удалось",
    nativePreserved: "Нативная работа остаётся доступной во время восстановления",
    fullSetupAction: "Запустить полную настройку подключений",
    fullSetupBody: "Повторно настройте сохранённые учётные данные и подключения, затем проверьте их. Это шире восстановления транспорта и не доказывает реальное выполнение инструмента.",
    blockedActiveWork: "Дождитесь завершения активной работы перед восстановлением Web-транспорта",
  },
  insights: {
    title: "Наблюдаемая производительность",
    body: "Сравнение использует локально записанные результаты за выбранный период. Это не лимит провайдера и не рекомендация по маршрутизации.",
    completionRate: "Доля завершений среди известных результатов",
    median: "Медианная длительность",
    p95: "95-й процентиль длительности",
    knownOutcomes: "Известных результатов: {count}",
    durationSamples: "Замеров длительности: {count}",
    coverage: "Покрытие наблюдаемой выборки: {count}",
    insufficientEvidence: "Недостаточно данных для надёжного сравнения",
    unknownIdentity: "Аккаунт или модель не были указаны; NEKODEX их не угадывал",
    noComparison: "За этот период нет сопоставимых наблюдаемых групп",
    notBestModel: "Эти наблюдения не определяют и не рекомендуют лучшую модель",
  },
};

const zhCN: WorkflowCopy = {
  session: {
    verificationUnavailable: "无法验证",
    verificationUnavailableBody: "NEKODEX 无法检查此会话。这并不表示账号已退出登录。",
    lastVerifiedAt: "上次验证：{time}",
    verifiedCurrent: "已在当前会话中验证",
    verificationStale: "仅为上次已知验证；当前状态未知",
    signedOut: "已退出登录",
    retryVerification: "重试验证",
    checkingVerification: "正在检查…",
  },
  portfolio: {
    refreshAll: "刷新账号限制",
    refreshing: "正在刷新账号限制…",
    summary: "当前数据 {updated} · 较早数据 {retained} · 不可用 {unavailable} · 已跳过 {skipped}",
    updatedCount: "当前证据：{count}",
    retainedCount: "保留上次结果：{count}",
    unavailableCount: "不可用：{count}",
    skippedCount: "已跳过：{count}",
    quotaCurrent: "提供方当前报告的时间窗口；并非账号总容量",
    quotaLastKnown: "提供方上次报告的时间窗口；并非当前状态或账号总容量",
    quotaUnavailable: "无法检查提供方限制",
    checkedAt: "提供方数据时间：{time}",
    retainedAt: "上次成功检查：{time}",
  },
  recovery: {
    webTransportTitle: "Web 传输需要处理",
    webTransportBody: "原生模型仍然可用。修复仅检查 Web 隧道，并不能证明工具已执行。",
    repairAction: "修复 Web 传输",
    repairing: "正在修复 Web 传输…",
    recovered: "Web 传输已修复并再次验证",
    stillUnavailable: "修复已完成，但 Web 传输仍不可用",
    couldNotVerify: "修复已完成，但无法验证就绪状态",
    nativePreserved: "修复期间原生工作仍然可用",
    fullSetupAction: "运行完整连接设置",
    fullSetupBody: "重新配置已保存的凭据和连接，然后进行验证。此操作范围大于传输修复，也不能证明工具实际执行。",
    blockedActiveWork: "请等待当前工作完成后再修复 Web 传输",
  },
  insights: {
    title: "观测到的性能",
    body: "比较基于所选时段内的本地记录结果，并非提供方限额或路由建议。",
    completionRate: "已知结果完成率",
    median: "时长中位数",
    p95: "时长第 95 百分位",
    knownOutcomes: "已知结果：{count}",
    durationSamples: "时长样本：{count}",
    coverage: "观测样本覆盖：{count}",
    insufficientEvidence: "证据不足，无法进行可靠比较",
    unknownIdentity: "账号或模型身份未上报，系统未进行猜测",
    noComparison: "此时段内没有可比较的观测组",
    notBestModel: "这些观测结果不会判定或推荐最佳模型",
  },
};

const zhTW: WorkflowCopy = {
  session: {
    verificationUnavailable: "無法驗證",
    verificationUnavailableBody: "NEKODEX 無法檢查此工作階段。這不表示帳號已登出。",
    lastVerifiedAt: "上次驗證：{time}",
    verifiedCurrent: "已在目前工作階段驗證",
    verificationStale: "僅為上次已知驗證；目前狀態未知",
    signedOut: "已登出",
    retryVerification: "重試驗證",
    checkingVerification: "正在檢查…",
  },
  portfolio: {
    refreshAll: "重新整理帳號限制",
    refreshing: "正在重新整理帳號限制…",
    summary: "目前資料 {updated} · 較早資料 {retained} · 無法使用 {unavailable} · 已略過 {skipped}",
    updatedCount: "目前證據：{count}",
    retainedCount: "保留上次結果：{count}",
    unavailableCount: "無法使用：{count}",
    skippedCount: "已略過：{count}",
    quotaCurrent: "提供者目前回報的時間窗；並非帳號總容量",
    quotaLastKnown: "提供者上次回報的時間窗；並非目前狀態或帳號總容量",
    quotaUnavailable: "無法檢查提供者限制",
    checkedAt: "提供者資料時間：{time}",
    retainedAt: "上次成功檢查：{time}",
  },
  recovery: {
    webTransportTitle: "Web 傳輸需要處理",
    webTransportBody: "原生模型仍可使用。修復只會檢查 Web 通道，並不證明工具已執行。",
    repairAction: "修復 Web 傳輸",
    repairing: "正在修復 Web 傳輸…",
    recovered: "Web 傳輸已修復並再次驗證",
    stillUnavailable: "修復已完成，但 Web 傳輸仍無法使用",
    couldNotVerify: "修復已完成，但無法驗證就緒狀態",
    nativePreserved: "修復期間原生工作仍可使用",
    fullSetupAction: "執行完整連線設定",
    fullSetupBody: "重新設定已儲存的憑證和連線，然後進行驗證。此操作範圍大於傳輸修復，也不證明工具實際執行。",
    blockedActiveWork: "請等待目前工作完成後再修復 Web 傳輸",
  },
  insights: {
    title: "觀測到的效能",
    body: "比較以所選期間的本機記錄結果為準，並非提供者限額或路由建議。",
    completionRate: "已知結果完成率",
    median: "時間中位數",
    p95: "時間第 95 百分位",
    knownOutcomes: "已知結果：{count}",
    durationSamples: "時間樣本：{count}",
    coverage: "觀測樣本涵蓋數：{count}",
    insufficientEvidence: "證據不足，無法可靠比較",
    unknownIdentity: "帳號或模型身分未回報，系統未加以猜測",
    noComparison: "此期間沒有可比較的觀測群組",
    notBestModel: "這些觀測不會判定或推薦最佳模型",
  },
};

const ja: WorkflowCopy = {
  session: {
    verificationUnavailable: "確認できません",
    verificationUnavailableBody: "NEKODEX はこのセッションを確認できませんでした。サインアウトしたことを意味しません。",
    lastVerifiedAt: "前回の確認: {time}",
    verifiedCurrent: "現在のセッションで確認済み",
    verificationStale: "前回確認時の状態です。現在の状態は不明です",
    signedOut: "サインアウト済み",
    retryVerification: "確認を再試行",
    checkingVerification: "確認中…",
  },
  portfolio: {
    refreshAll: "アカウント制限を更新",
    refreshing: "アカウント制限を更新中…",
    summary: "現在のデータ {updated} · 以前のデータ {retained} · 利用不可 {unavailable} · スキップ {skipped}",
    updatedCount: "現在の証拠: {count}",
    retainedCount: "前回値を保持: {count}",
    unavailableCount: "利用不可: {count}",
    skippedCount: "スキップ: {count}",
    quotaCurrent: "プロバイダーが現在報告する期間別制限です。アカウントの総容量ではありません",
    quotaLastKnown: "プロバイダーが前回報告した期間別制限です。現在値でも総容量でもありません",
    quotaUnavailable: "プロバイダー制限を確認できませんでした",
    checkedAt: "プロバイダーデータの日時: {time}",
    retainedAt: "前回の確認成功: {time}",
  },
  recovery: {
    webTransportTitle: "Web 通信の確認が必要です",
    webTransportBody: "ネイティブモデルは引き続き利用できます。修復は Web トンネルだけを確認し、ツールの実行を証明しません。",
    repairAction: "Web 通信を修復",
    repairing: "Web 通信を修復中…",
    recovered: "Web 通信を修復し、再確認しました",
    stillUnavailable: "修復は完了しましたが、Web 通信はまだ利用できません",
    couldNotVerify: "修復は完了しましたが、準備状態を確認できませんでした",
    nativePreserved: "修復中もネイティブ処理は利用できます",
    fullSetupAction: "接続をすべて設定",
    fullSetupBody: "保存済みの認証情報と接続を再設定してから確認します。通信だけの修復より広い操作であり、実際のツール実行を証明しません。",
    blockedActiveWork: "実行中の処理が完了してから Web 通信を修復してください",
  },
  insights: {
    title: "観測されたパフォーマンス",
    body: "選択期間にローカルで記録された結果の比較です。プロバイダーの利用枠やルーティング推奨ではありません。",
    completionRate: "結果判明分の完了率",
    median: "所要時間の中央値",
    p95: "所要時間の95パーセンタイル",
    knownOutcomes: "結果判明数: {count}",
    durationSamples: "所要時間サンプル: {count}",
    coverage: "観測サンプル範囲: {count}",
    insufficientEvidence: "信頼できる比較に必要なデータが不足しています",
    unknownIdentity: "アカウントまたはモデルは報告されておらず、推測していません",
    noComparison: "この期間に比較可能な観測グループはありません",
    notBestModel: "この観測から最良のモデルを判定または推奨することはできません",
  },
};

const ko: WorkflowCopy = {
  session: {
    verificationUnavailable: "확인할 수 없음",
    verificationUnavailableBody: "NEKODEX가 이 세션을 확인하지 못했습니다. 계정에서 로그아웃되었다는 뜻은 아닙니다.",
    lastVerifiedAt: "마지막 확인: {time}",
    verifiedCurrent: "현재 세션에서 확인됨",
    verificationStale: "마지막으로 확인된 상태이며 현재 상태는 알 수 없음",
    signedOut: "로그아웃됨",
    retryVerification: "확인 다시 시도",
    checkingVerification: "확인 중…",
  },
  portfolio: {
    refreshAll: "계정 한도 새로 고침",
    refreshing: "계정 한도 새로 고치는 중…",
    summary: "현재 데이터 {updated} · 이전 데이터 {retained} · 사용 불가 {unavailable} · 건너뜀 {skipped}",
    updatedCount: "현재 근거: {count}",
    retainedCount: "마지막 결과 유지: {count}",
    unavailableCount: "사용 불가: {count}",
    skippedCount: "건너뜀: {count}",
    quotaCurrent: "제공자가 현재 보고한 기간별 한도이며 계정의 총용량이 아님",
    quotaLastKnown: "제공자가 마지막으로 보고한 기간별 한도이며 현재 상태나 계정 총용량이 아님",
    quotaUnavailable: "제공자 한도를 확인할 수 없음",
    checkedAt: "제공자 데이터 시각: {time}",
    retainedAt: "마지막 확인 성공: {time}",
  },
  recovery: {
    webTransportTitle: "Web 전송 확인 필요",
    webTransportBody: "네이티브 모델은 계속 사용할 수 있습니다. 복구는 Web 터널만 확인하며 도구 실행을 증명하지 않습니다.",
    repairAction: "Web 전송 복구",
    repairing: "Web 전송 복구 중…",
    recovered: "Web 전송을 복구하고 다시 확인함",
    stillUnavailable: "복구가 끝났지만 Web 전송을 아직 사용할 수 없음",
    couldNotVerify: "복구가 끝났지만 준비 상태를 확인할 수 없음",
    nativePreserved: "복구 중에도 네이티브 작업을 사용할 수 있음",
    fullSetupAction: "전체 연결 설정 실행",
    fullSetupBody: "저장된 자격 증명과 연결을 다시 구성한 뒤 확인합니다. 전송 복구보다 범위가 넓으며 실제 도구 실행을 증명하지 않습니다.",
    blockedActiveWork: "진행 중인 작업이 끝난 뒤 Web 전송을 복구하세요",
  },
  insights: {
    title: "관측된 성능",
    body: "선택한 기간에 로컬로 기록된 결과를 비교합니다. 제공자 사용 한도나 라우팅 권장 사항이 아닙니다.",
    completionRate: "결과가 확인된 작업의 완료율",
    median: "소요 시간 중앙값",
    p95: "소요 시간 95백분위수",
    knownOutcomes: "확인된 결과: {count}",
    durationSamples: "소요 시간 샘플: {count}",
    coverage: "관측 샘플 범위: {count}",
    insufficientEvidence: "신뢰할 수 있는 비교를 위한 데이터가 부족함",
    unknownIdentity: "계정 또는 모델 정보가 보고되지 않았으며 추측하지 않음",
    noComparison: "이 기간에는 비교 가능한 관측 그룹이 없음",
    notBestModel: "이 관측 결과는 최적 모델을 판정하거나 권장하지 않음",
  },
};

export function workflowCopy(language: Language): WorkflowCopy {
  if (language === "ru") return ru;
  if (language === "zh-CN") return zhCN;
  if (language === "zh-TW") return zhTW;
  if (language === "ja") return ja;
  if (language === "ko") return ko;
  return en;
}
